title: AP Comp Sci Final Website
author: Suket Shah
email: suketsshah12@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is for the AP Computer Science Final Website project.

# social links
twitter_username: suketshah3
github_username:  suketshah17

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
